### ISSUE TITLE
Actionsを使ってデプロイを自動化したい

### ISSUE THREAD

**Issue by uzimaru0000** [uzimaru0000/uzimaru.com#15]

**Comment by ry-itto** [comment]
公開したくない値とか扱う場合は載せた記事みたいにすればいけるのでもしよければ参考にしてもらえれば！
https://qiita.com/ry-itto/items/0fab3fdc4321bfbd3877#%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AB%E7%99%BB%E9%8C%B2%E3%81%99%E3%82%8B

**Comment by uzimaru0000** [comment]
ありがとう！！

**Comment by uzimaru0000** [comment]
vercelのapp経由でvercelにデプロイするようにした
